// AUTH TYPES
export const AUTH_LOGIN_USER = 'AUTH_LOGIN_USER';
export const AUTH_LOGIN_USER_FAIL = 'AUTH_LOGIN_USER_FAIL';
export const AUTH_LOGIN_USER_SUCCESS = 'AUTH_LOGIN_USER_SUCCESS';
export const AUTH_CREATE_USER = 'AUTH_CREATE_USER';
export const AUTH_CREATE_USER_FAIL = 'AUTH_CREATE_USER_FAIL';
export const AUTH_CREATE_USER_SUCCESS = 'AUTH_CREATE_USER_SUCCESS';

//AUTH USER CREATION TYPES
export const AUTH_NAME_INFO_ADD = 'AUTH_NAME_INFO_ADD';
export const AUTH_CONSENT_INFO_ADD = 'AUTH_CONSENT_INFO_ADD';
export const AUTH_HEIGHT_INFO_ADD = 'AUTH_HEIGHT_INFO_ADD';
export const AUTH_WEIGHT_INFO_ADD = 'AUTH_WEIGHT_INFO_ADD';
export const AUTH_ACTIVITY_LEVEL_INFO = 'AUTH_ACTIVITY_LEVEL_INFO';
export const AUTH_GOAL_INFO_ADD = 'AUTH_GOAL_INFO_ADD';
export const AUTH_BMI_INFO = 'AUTH_BMI_INFO';
export const AUTH_LOGOUT_USER = 'AUTH_LOGOUT_USER';
export const AUTH_LOGOUT_USER_FAIL = 'AUTH_LOGOUT_USER_FAIL';
export const AUTH_LOGOUT_USER_SUCCESS = 'AUTH_LOGOUT_USER_SUCCESS';
export const AUTH_IMAGE_INFO = 'AUTH_IMAGE_INFO';

// PROFILE TYPES
export const PROFILE_FETCH = 'PROFILE_FETCH';
export const PROFILE_EDIT = 'PROFILE_EDIT';

// ACTIVITY
export const ACTIVITY_ADD_INFO = 'ACTIVITY_ADD_INFO';
export const ACTIVITY_FETCH = 'ACTIVITY_FETCH';
export const ACTIVITY_COMPLETE_INFO = 'ACTIVITY_COMPLETE_INFO';
export const ACTIVITY_FETCH_STATS = 'ACTIVITY_FETCH_STATS';
